CC = g++
CFLAGS = -c -Wall
LDFLAGS = -lpthread
SOURCES = Server.cpp TCPStream.cpp TCPServer.cpp
OBJECTS = $(SOURCES:.cpp=.o)
EXECUTABLE = Server

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -rf $(OBJECTS) $(EXECUTABLE)
