CC = g++
CFLAGS = -c -Wall
LDFLAGS =
SOURCES = Client.cpp TCPStream.cpp TCPClient.cpp
OBJECTS = $(SOURCES:.cpp=.o)
EXECUTABLE = Client

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm -rf $(OBJECTS) $(EXECUTABLE)
